const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={route:'today',settings:{practicum:'Prácticum I',hospital:'Hospital La Fe',service:'',periodStart:'2026-09-21',periodEnd:'2026-11-27',shift:'15:00–22:00',icdWorker:''}, procedures:[
  'Higiene de manos','Toma de constantes','Glucemia capilar','Administración oral','Administración subcutánea','Administración intramuscular','Administración intravenosa','Canalización de vía periférica','Extracción sanguínea','Hemocultivos','Oxigenoterapia','Nebulización','Cura de heridas','Cambio de apósito','Sondaje vesical','Sondaje nasogástrico','Balance hídrico','ECG de 12 derivaciones','Movilización y transferencias','Prevención de UPP'
]};
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const id=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;
const fmtDate=d=>new Intl.DateTimeFormat('es-ES',{day:'numeric',month:'short',year:'numeric'}).format(new Date(`${d}T12:00:00`));
const todayISO=()=>new Date().toISOString().slice(0,10);
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.add('hidden'),2200)}
function modal(html){$('#modalContent').innerHTML=html;$('#modal').showModal()} function closeModal(){if($('#modal').open)$('#modal').close()}
function section(title,action=''){return `<div class="section-head"><h2>${title}</h2>${action}</div>`}
function pct(a,b){return b?Math.min(100,Math.round(a/b*100)):0}

async function boot(){
  await NurseDB.open(); const saved=await NurseDB.get('settings','main'); if(saved) state.settings={...state.settings,...saved.value};
  await seed(); bindNav(); registerSW(); render(); setupInstall();
}
async function seed(){
  if((await NurseDB.all('procedures')).length===0){for(const name of state.procedures) await NurseDB.put('procedures',{id:name.toLowerCase().replace(/\s+/g,'-'),name,materials:[],notes:'',favorite:false});}
}
function bindNav(){ $$('.nav-item').forEach(b=>b.onclick=()=>{state.route=b.dataset.route;$$('.nav-item').forEach(x=>x.classList.toggle('active',x===b));render();window.scrollTo(0,0)}); $('#quickSearchBtn').onclick=openGlobalSearch; }
function registerSW(){if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(console.warn)}
function setupInstall(){let prompt;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();prompt=e;$('#installBanner').classList.remove('hidden')});$('#installBtn').onclick=async()=>{if(prompt){prompt.prompt();await prompt.userChoice;prompt=null;$('#installBanner').classList.add('hidden')}};$('#installClose').onclick=()=>$('#installBanner').classList.add('hidden')}

async function render(){const map={today:renderToday,university:renderUniversity,practicum:renderPracticum,consult:renderConsult,study:renderStudy};const titles={today:'Hoy',university:'Universidad',practicum:'Prácticum',consult:'Consulta',study:'Estudio'};$('#pageTitle').textContent=titles[state.route];$('#contextLabel').textContent=state.route==='practicum'?state.settings.practicum:'NurseFlow';await map[state.route]();}

async function renderToday(){
  const cases=await NurseDB.all('cases'), tasks=await NurseDB.all('tasks'); const today=cases.filter(x=>x.date===todayISO());
  const start=new Date(state.settings.periodStart+'T12:00:00'), end=new Date(state.settings.periodEnd+'T12:00:00'), now=new Date(); const prog=Math.max(0,Math.min(100,Math.round((now-start)/(end-start)*100)));
  $('#app').innerHTML=`
  <div class="card hero"><p class="small muted">${esc(state.settings.hospital)} · ${esc(state.settings.shift)}</p><h2>${esc(state.settings.practicum)}</h2><p>${fmtDate(state.settings.periodStart)} → ${fmtDate(state.settings.periodEnd)}</p><div class="progress"><span style="width:${prog}%"></span></div><p class="small muted">Progreso temporal aproximado ${prog}%</p><button class="btn secondary" id="todayLog">Registrar día</button></div>
  ${section('Accesos rápidos')}
  <div class="grid-2"><button class="quick" data-jump="practicum"><span>＋</span><strong>Nuevo caso</strong></button><button class="quick" data-jump="consult"><span>✚</span><strong>La Batea</strong></button><button class="quick" id="medQuick"><span>Rx</span><strong>Medicamentos</strong></button><button class="quick" id="calcQuick"><span>÷</span><strong>Calculadoras</strong></button></div>
  ${section('Hoy')}
  <div class="card compact"><div class="grid-3"><div class="stat"><b>${today.length}</b><span class="small muted">casos</span></div><div class="stat"><b>${cases.reduce((n,c)=>n+(c.procedures?.length||0),0)}</b><span class="small muted">procedimientos</span></div><div class="stat"><b>${tasks.filter(t=>!t.done).length}</b><span class="small muted">pendientes</span></div></div></div>
  <div class="notice">La app es una herramienta académica y organizativa. No sustituye protocolos del centro, ficha técnica, supervisión clínica ni UCVEvalúa.</div>`;
  $('#todayLog').onclick=openDayLog; $$('[data-jump]').forEach(b=>b.onclick=()=>{$(`[data-route="${b.dataset.jump}"]`).click()}); $('#medQuick').onclick=()=>{state.route='consult';syncNav();render().then(()=>openMedSearch())}; $('#calcQuick').onclick=()=>{state.route='consult';syncNav();render().then(()=>openCalculator())};
}
function syncNav(){$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.route===state.route))}

async function renderUniversity(){
  const schedule=(await NurseDB.all('schedule')).sort((a,b)=>(a.day+a.start).localeCompare(b.day+b.start));
  $('#app').innerHTML=`${section('Semana tipo','<button id="addClass">Añadir</button>')}<div class="card"><p class="muted small">Configura una semana base. Esta primera versión guarda la plantilla localmente; las excepciones por fecha se añadirán en la siguiente iteración.</p><div id="scheduleList" class="list"></div></div>
  ${section('Académico')}<div class="grid-2"><button class="quick" id="deadlines"><span>✓</span><strong>Pendientes</strong></button><button class="quick" id="nanda"><span>PAE</span><strong>NANDA · NIC · NOC</strong></button><button class="quick" data-route2="study"><span>◫</span><strong>Flashcards</strong></button><button class="quick" id="calendarInfo"><span>▦</span><strong>Calendario</strong></button></div>`;
  $('#scheduleList').innerHTML=schedule.length?schedule.map(x=>`<div class="list-row"><div class="grow"><strong>${['Dom','Lun','Mar','Mié','Jue','Vie','Sáb'][x.day]} · ${esc(x.title)}</strong><span class="small muted">${esc(x.start)}–${esc(x.end)} ${x.room?`· ${esc(x.room)}`:''}</span></div><button class="icon-btn" data-del-class="${x.id}">×</button></div>`).join(''):'<div class="empty">Todavía no has configurado tu semana.</div>';
  $('#addClass').onclick=openAddClass; $$('[data-del-class]').forEach(b=>b.onclick=async()=>{await NurseDB.remove('schedule',b.dataset.delClass);render()}); $('[data-route2="study"]').onclick=()=>{$('[data-route="study"]').click()}; $('#nanda').onclick=()=>toast('Módulo preparado para incorporar una fuente/licencia válida.'); $('#deadlines').onclick=openTasks; $('#calendarInfo').onclick=()=>toast('La vista de calendario ampliada queda preparada para la siguiente versión.');
}
function openAddClass(){modal(`<div class="modal-head"><h2>Añadir a semana tipo</h2><button class="icon-btn" onclick="closeModal()">×</button></div><form id="classForm"><label>Asignatura / actividad</label><input class="field" name="title" required><div class="form-row"><div><label>Día</label><select class="field" name="day">${['Domingo','Lunes','Martes','Miércoles','Jueves','Viernes','Sábado'].map((x,i)=>`<option value="${i}" ${i===1?'selected':''}>${x}</option>`).join('')}</select></div><div><label>Aula</label><input class="field" name="room"></div></div><div class="form-row"><div><label>Inicio</label><input class="field" type="time" name="start" required></div><div><label>Fin</label><input class="field" type="time" name="end" required></div></div><div class="modal-actions"><button type="button" class="btn" onclick="closeModal()">Cancelar</button><button class="btn primary">Guardar</button></div></form>`); $('#classForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);await NurseDB.put('schedule',{id:id(),title:f.get('title'),day:Number(f.get('day')),room:f.get('room'),start:f.get('start'),end:f.get('end')});closeModal();render();toast('Guardado')};}

async function renderPracticum(){
  const cases=(await NurseDB.all('cases')).sort((a,b)=>b.date.localeCompare(a.date)); const procs=cases.flatMap(c=>c.procedures||[]); const distinct=new Set(procs.map(p=>p.name)).size;
  $('#app').innerHTML=`<div class="card hero"><p class="small muted">${esc(state.settings.hospital)} ${state.settings.service?'· '+esc(state.settings.service):''}</p><h2>${esc(state.settings.practicum)}</h2><p>${fmtDate(state.settings.periodStart)} → ${fmtDate(state.settings.periodEnd)} · ${esc(state.settings.shift)}</p><button class="btn secondary" id="settingsPrac">Configurar prácticum</button></div>
  <div class="grid-3"><div class="stat"><b>${cases.length}</b><span class="small muted">casos</span></div><div class="stat"><b>${procs.length}</b><span class="small muted">experiencias</span></div><div class="stat"><b>${distinct}</b><span class="small muted">técnicas</span></div></div>
  <button class="btn primary block" id="newDay" style="margin-top:12px">Registrar día / caso</button>
  ${section('Diario de casos')}<div class="list" id="caseList"></div>
  ${section('Portfolio de procedimientos','<button id="portfolioBtn">Ver</button>')}<div class="card compact"><p class="muted small">Agrupa automáticamente lo observado, ayudado y realizado para preparar tutorías y memoria.</p></div>
  ${section('Requisitos UCV')}<div class="card compact"><label class="check-row"><input type="checkbox" id="attCheck"> <span>He registrado la asistencia oficial en UCVEvalúa hoy</span></label><p class="small muted">La asistencia oficial se registra en UCVEvalúa; NurseFlow solo sirve como recordatorio personal.</p></div>`;
  $('#caseList').innerHTML=cases.length?cases.slice(0,12).map(c=>`<button class="list-row" data-case="${c.id}"><div class="grow" style="text-align:left"><strong>${esc(c.diagnosis||'Caso sin diagnóstico')}</strong><span class="small muted">${fmtDate(c.date)} · ${(c.procedures||[]).length} procedimiento(s)</span></div><span>›</span></button>`).join(''):'<div class="empty">Aún no has registrado casos.</div>';
  $('#newDay').onclick=openDayLog; $('#settingsPrac').onclick=openPracticumSettings; $('#portfolioBtn').onclick=openPortfolio; $$('[data-case]').forEach(b=>b.onclick=()=>openCase(b.dataset.case)); const att=await NurseDB.get('days',`attendance-${todayISO()}`); $('#attCheck').checked=!!att?.done; $('#attCheck').onchange=e=>NurseDB.put('days',{id:`attendance-${todayISO()}`,done:e.target.checked,date:todayISO()});
}
function procedureInputs(selected=[]){return `<div id="procRows">${selected.map((p,i)=>procRow(p,i)).join('')}</div><button type="button" class="btn secondary block" id="addProc">+ Añadir procedimiento</button>`}
function procRow(p={},i=0){return `<div class="card compact proc-row" data-i="${i}"><label>Procedimiento</label><input class="field proc-name" list="procList" value="${esc(p.name||'')}"><label>Participación</label><select class="field proc-role"><option ${p.role==='Observado'?'selected':''}>Observado</option><option ${p.role==='Ayudado'?'selected':''}>Ayudado</option><option ${p.role==='Realizado con supervisión'?'selected':''}>Realizado con supervisión</option><option ${p.role==='Realizado'?'selected':''}>Realizado</option><option ${p.role==='Realizado por enfermería/otro profesional'?'selected':''}>Realizado por enfermería/otro profesional</option></select><button type="button" class="btn danger proc-remove" style="margin-top:10px">Quitar</button></div>`}
function datalist(){return `<datalist id="procList">${state.procedures.map(x=>`<option value="${esc(x)}">`).join('')}</datalist>`}
function wireProcRows(){let n=$$('.proc-row').length;$('#addProc').onclick=()=>{$('#procRows').insertAdjacentHTML('beforeend',procRow({},n++));wireRemove()};wireRemove();function wireRemove(){$$('.proc-remove').forEach(b=>b.onclick=()=>b.closest('.proc-row').remove())}}
function collectProcs(){return $$('.proc-row').map(r=>({name:r.querySelector('.proc-name').value.trim(),role:r.querySelector('.proc-role').value})).filter(x=>x.name)}
function openDayLog(){modal(`<div class="modal-head"><h2>Registrar caso</h2><button class="icon-btn" onclick="closeModal()">×</button></div><form id="caseForm"><label>Fecha</label><input class="field" type="date" name="date" value="${todayISO()}" required><label>Patología / diagnóstico</label><div style="display:flex;gap:8px"><input class="field" id="diagnosis" name="diagnosis" placeholder="Ej. neumonía" required><button type="button" class="btn" id="icdBtn">CIE</button></div><input type="hidden" name="icdCode" id="icdCode"><p id="icdChosen" class="small muted"></p><label>Contexto clínico anonimizado</label><textarea class="field" name="context" placeholder="Solo información académicamente relevante. No incluyas datos identificativos."></textarea><h3 style="margin-top:18px">Procedimientos</h3>${procedureInputs([])}${datalist()}<label>Medicamentos relacionados (opcional)</label><input class="field" name="meds" placeholder="Separados por comas"><label>¿Qué he aprendido?</label><textarea class="field" name="learned"></textarea><label>¿Qué quiero revisar?</label><textarea class="field" name="review"></textarea><label class="check-row"><input type="checkbox" name="memory"> <span>Marcar como relevante para la memoria</span></label><div class="notice">No introduzcas nombre, iniciales, SIP, historia clínica, habitación/cama, fotografías ni otros datos que permitan identificar al paciente.</div><div class="modal-actions"><button type="button" class="btn" onclick="closeModal()">Cancelar</button><button class="btn primary">Guardar</button></div></form>`);wireProcRows();$('#icdBtn').onclick=()=>openICDSearch($('#diagnosis').value);$('#caseForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);await NurseDB.put('cases',{id:id(),date:f.get('date'),diagnosis:f.get('diagnosis'),icdCode:f.get('icdCode'),context:f.get('context'),procedures:collectProcs(),meds:f.get('meds').split(',').map(x=>x.trim()).filter(Boolean),learned:f.get('learned'),review:f.get('review'),memory:f.get('memory')==='on',createdAt:new Date().toISOString()});closeModal();render();toast('Caso guardado en este dispositivo')};}
async function openCase(caseId){const c=await NurseDB.get('cases',caseId);if(!c)return;modal(`<div class="modal-head"><h2>${esc(c.diagnosis)}</h2><button class="icon-btn" onclick="closeModal()">×</button></div><p class="muted">${fmtDate(c.date)} ${c.icdCode?`· CIE ${esc(c.icdCode)}`:''}</p>${c.context?`<div class="card compact"><strong>Contexto</strong><p>${esc(c.context)}</p></div>`:''}<h3>Procedimientos</h3><div class="list">${(c.procedures||[]).map(p=>`<div class="list-row"><div class="grow"><strong>${esc(p.name)}</strong><span class="small muted">${esc(p.role)}</span></div></div>`).join('')||'<p class="muted">Ninguno.</p>'}</div>${c.learned?`<h3>Aprendizaje</h3><p>${esc(c.learned)}</p>`:''}${c.review?`<h3>Para revisar</h3><p>${esc(c.review)}</p>`:''}<div class="modal-actions"><button class="btn danger" id="deleteCase">Eliminar</button><button class="btn" onclick="closeModal()">Cerrar</button></div>`);$('#deleteCase').onclick=async()=>{if(confirm('¿Eliminar este caso?')){await NurseDB.remove('cases',caseId);closeModal();render();}}}
async function openPortfolio(){const cases=await NurseDB.all('cases');const m={};cases.forEach(c=>(c.procedures||[]).forEach(p=>{m[p.name]??={total:0,roles:{}};m[p.name].total++;m[p.name].roles[p.role]=(m[p.name].roles[p.role]||0)+1;}));const rows=Object.entries(m).sort((a,b)=>b[1].total-a[1].total);modal(`<div class="modal-head"><h2>Portfolio de procedimientos</h2><button class="icon-btn" onclick="closeModal()">×</button></div>${rows.length?rows.map(([name,x])=>`<div class="card compact"><strong>${esc(name)}</strong><p class="small muted">${x.total} experiencia(s)</p>${Object.entries(x.roles).map(([r,n])=>`<span class="pill" style="margin:2px">${esc(r)} · ${n}</span>`).join('')}</div>`).join(''):'<div class="empty">Registra procedimientos para construir tu portfolio.</div>'}`)}
function openPracticumSettings(){const s=state.settings;modal(`<div class="modal-head"><h2>Configurar prácticum</h2><button class="icon-btn" onclick="closeModal()">×</button></div><form id="pracForm"><label>Prácticum</label><input class="field" name="practicum" value="${esc(s.practicum)}"><label>Centro</label><input class="field" name="hospital" value="${esc(s.hospital)}"><label>Servicio (cuando lo sepas)</label><input class="field" name="service" value="${esc(s.service)}"><div class="form-row"><div><label>Inicio</label><input class="field" type="date" name="periodStart" value="${s.periodStart}"></div><div><label>Fin</label><input class="field" type="date" name="periodEnd" value="${s.periodEnd}"></div></div><label>Horario</label><input class="field" name="shift" value="${esc(s.shift)}"><label>URL Worker CIE (opcional)</label><input class="field" name="icdWorker" value="${esc(s.icdWorker)}" placeholder="https://...workers.dev"><div class="modal-actions"><button class="btn primary">Guardar</button></div></form>`);$('#pracForm').onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));state.settings={...state.settings,...f};await NurseDB.put('settings',{id:'main',value:state.settings});closeModal();render();toast('Configuración guardada')};}

async function renderConsult(){
  $('#app').innerHTML=`<div class="grid-2"><button class="quick" id="meds"><span>Rx</span><strong>Medicamentos</strong></button><button class="quick" id="batea"><span>✚</span><strong>La Batea</strong></button><button class="quick" id="calcs"><span>÷</span><strong>Calculadoras</strong></button><button class="quick" id="scales"><span>Σ</span><strong>Escalas</strong></button><button class="quick" id="labs"><span>↟</span><strong>Analíticas</strong></button><button class="quick" id="terms"><span>ABC</span><strong>Diccionario</strong></button></div>${section('Consulta rápida')}<div class="notice">Contenido orientativo para aprendizaje. Verifica siempre protocolos de la unidad, rangos del laboratorio y ficha técnica vigente antes de tomar decisiones clínicas.</div>`;
  $('#meds').onclick=openMedSearch;$('#batea').onclick=openBatea;$('#calcs').onclick=openCalculator;$('#scales').onclick=openScales;$('#labs').onclick=()=>toast('Base de analíticas preparada para la siguiente versión.');$('#terms').onclick=()=>toast('Diccionario preparado para la siguiente versión.');
}
function openMedSearch(){modal(`<div class="modal-head"><h2>Medicamentos · CIMA</h2><button class="icon-btn" onclick="closeModal()">×</button></div><label>Buscar medicamento</label><div style="display:flex;gap:8px"><input class="field" id="medQuery" placeholder="Ej. paracetamol"><button class="btn primary" id="medSearchBtn">Buscar</button></div><div id="medResults" style="margin-top:12px"></div><p class="small muted">Fuente: CIMA / AEMPS. La app no interpreta ni convierte automáticamente la ficha técnica en instrucciones de administración.</p>`);$('#medSearchBtn').onclick=async()=>{const q=$('#medQuery').value.trim();if(q.length<2)return;$('#medResults').innerHTML='<div class="empty">Buscando…</div>';try{const r=await fetch(`https://cima.aemps.es/cima/rest/medicamentos?nombre=${encodeURIComponent(q)}`);if(!r.ok)throw new Error('Respuesta CIMA '+r.status);const j=await r.json();const arr=j.resultados||j.results||j||[];$('#medResults').innerHTML=(Array.isArray(arr)&&arr.length)?arr.slice(0,15).map(m=>`<button class="list-row med-result" data-nreg="${esc(m.nregistro||'')}" data-name="${esc(m.nombre||m.name||q)}"><div class="grow" style="text-align:left"><strong>${esc(m.nombre||m.name||'Medicamento')}</strong><span class="small muted">${esc(m.labtitular||m.labtitular?.nombre||m.nregistro||'')}</span></div><span>›</span></button>`).join(''):'<div class="empty">Sin resultados.</div>';$$('.med-result').forEach(b=>b.onclick=()=>openMedDetail(b.dataset.nreg,b.dataset.name));}catch(e){$('#medResults').innerHTML=`<div class="notice">No se pudo consultar CIMA desde este navegador. ${esc(e.message)}</div>`}}}
async function openMedDetail(nreg,name){try{const r=await fetch(`https://cima.aemps.es/cima/rest/medicamento?nregistro=${encodeURIComponent(nreg)}`);const m=await r.json();const princ=(m.principiosActivos||[]).map(x=>x.nombre).join(', ');await NurseDB.put('meds',{id:nreg||name,name:m.nombre||name,nregistro:nreg,principios:princ,raw:m,cachedAt:new Date().toISOString()});modal(`<div class="modal-head"><h2>${esc(m.nombre||name)}</h2><button class="icon-btn" onclick="closeModal()">×</button></div><span class="pill green">Guardado offline</span><p><strong>Principio(s) activo(s):</strong><br>${esc(princ||'No disponible')}</p><p><strong>Nº registro:</strong> ${esc(nreg)}</p><p class="small muted">Se conserva localmente la respuesta estructurada de CIMA. Para información de administración y seguridad clínica, consulta la ficha técnica oficial vigente.</p><button class="btn block" onclick="closeModal()">Cerrar</button>`);}catch(e){toast('No se pudo abrir el medicamento')}}
async function openBatea(){const procs=await NurseDB.all('procedures');modal(`<div class="modal-head"><h2>La Batea</h2><button class="icon-btn" onclick="closeModal()">×</button></div><input class="field" id="bateaFilter" placeholder="Buscar técnica"><div id="bateaList" class="list" style="margin-top:10px"></div>`);const paint=(q='')=>{$('#bateaList').innerHTML=procs.filter(p=>p.name.toLowerCase().includes(q.toLowerCase())).map(p=>`<button class="list-row" data-proc-id="${p.id}"><div class="grow" style="text-align:left"><strong>${esc(p.name)}</strong><span class="small muted">${(p.materials||[]).length} materiales · ${p.notes?'con notas':'sin notas'}</span></div><span>›</span></button>`).join('');$$('[data-proc-id]').forEach(b=>b.onclick=()=>openProcedure(b.dataset.procId));};paint();$('#bateaFilter').oninput=e=>paint(e.target.value)}
async function openProcedure(pid){const p=await NurseDB.get('procedures',pid);modal(`<div class="modal-head"><h2>${esc(p.name)}</h2><button class="icon-btn" onclick="closeModal()">×</button></div><form id="procForm"><label>Materiales (uno por línea)</label><textarea class="field" name="materials">${esc((p.materials||[]).join('\n'))}</textarea><label>Notas personales / protocolo de la unidad</label><textarea class="field" name="notes">${esc(p.notes||'')}</textarea><div class="notice">No guardes datos de pacientes. Las notas de unidad son recordatorios personales y no sustituyen el protocolo oficial.</div><div class="modal-actions"><button class="btn primary">Guardar</button></div></form>`);$('#procForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);p.materials=f.get('materials').split('\n').map(x=>x.trim()).filter(Boolean);p.notes=f.get('notes');await NurseDB.put('procedures',p);closeModal();toast('Batea actualizada')}}
function openCalculator(){modal(`<div class="modal-head"><h2>Calculadoras</h2><button class="icon-btn" onclick="closeModal()">×</button></div><div class="segmented"><button class="active" data-calc="flow">ml/h</button><button data-calc="drops">Goteo</button><button data-calc="bmi">IMC</button></div><div id="calcBody"></div><div class="notice">Herramientas educativas de cálculo. Revisa unidades, prescripción y protocolos antes de utilizar cualquier resultado en práctica clínica.</div>`);$$('[data-calc]').forEach(b=>b.onclick=()=>{$$('[data-calc]').forEach(x=>x.classList.remove('active'));b.classList.add('active');paintCalc(b.dataset.calc)});paintCalc('flow')}
function paintCalc(type){const body=$('#calcBody');if(type==='flow')body.innerHTML=`<label>Volumen (ml)</label><input class="field" id="v" inputmode="decimal"><label>Tiempo (horas)</label><input class="field" id="t" inputmode="decimal"><button class="btn primary block" style="margin:12px 0" id="go">Calcular</button><div id="result"></div>`;if(type==='drops')body.innerHTML=`<label>Volumen (ml)</label><input class="field" id="v" inputmode="decimal"><label>Tiempo (minutos)</label><input class="field" id="t" inputmode="decimal"><label>Factor de goteo (gotas/ml)</label><input class="field" id="f" inputmode="decimal" value="20"><button class="btn primary block" style="margin:12px 0" id="go">Calcular</button><div id="result"></div>`;if(type==='bmi')body.innerHTML=`<label>Peso (kg)</label><input class="field" id="v" inputmode="decimal"><label>Altura (cm)</label><input class="field" id="t" inputmode="decimal"><button class="btn primary block" style="margin:12px 0" id="go">Calcular</button><div id="result"></div>`;$('#go').onclick=()=>{const v=parseFloat($('#v').value.replace(',','.')),t=parseFloat($('#t').value.replace(',','.'));let out='';if(!(v>0&&t>0))out='Revisa los valores.';else if(type==='flow')out=`<div class="card compact"><b>${(v/t).toFixed(1)} ml/h</b><p class="small muted">Fórmula: volumen ÷ horas</p></div>`;else if(type==='drops'){const f=parseFloat($('#f').value.replace(',','.'));out=f>0?`<div class="card compact"><b>${((v*f)/t).toFixed(1)} gotas/min</b><p class="small muted">Fórmula: (ml × factor) ÷ minutos</p></div>`:'Revisa el factor.'}else{const m=t/100;out=`<div class="card compact"><b>IMC ${(v/(m*m)).toFixed(1)}</b><p class="small muted">Fórmula: kg ÷ m²</p></div>`}$('#result').innerHTML=out}}
function openScales(){modal(`<div class="modal-head"><h2>Escalas</h2><button class="icon-btn" onclick="closeModal()">×</button></div><div class="list"><button class="list-row" id="glasgow"><div class="grow" style="text-align:left"><strong>Glasgow</strong><span class="small muted">Apertura ocular + verbal + motora</span></div><span>›</span></button><div class="list-row"><div class="grow"><strong>Barthel / Norton / Braden</strong><span class="small muted">Preparadas para una siguiente versión con fuente y validación de criterios.</span></div></div></div>`);$('#glasgow').onclick=openGlasgow}
function openGlasgow(){modal(`<div class="modal-head"><h2>Escala de Glasgow</h2><button class="icon-btn" onclick="closeModal()">×</button></div><label>Apertura ocular</label><select class="field g"><option value="4">4 · Espontánea</option><option value="3">3 · A la voz</option><option value="2">2 · Al dolor</option><option value="1">1 · Ninguna</option></select><label>Respuesta verbal</label><select class="field g"><option value="5">5 · Orientada</option><option value="4">4 · Confusa</option><option value="3">3 · Palabras inapropiadas</option><option value="2">2 · Sonidos incomprensibles</option><option value="1">1 · Ninguna</option></select><label>Respuesta motora</label><select class="field g"><option value="6">6 · Obedece órdenes</option><option value="5">5 · Localiza dolor</option><option value="4">4 · Retirada</option><option value="3">3 · Flexión anormal</option><option value="2">2 · Extensión</option><option value="1">1 · Ninguna</option></select><div id="gRes" class="card compact"><b>15 puntos</b></div><div class="notice">Muestra únicamente la suma de la escala. La interpretación clínica depende del contexto y del protocolo asistencial.</div>`);const calc=()=>{$('#gRes').innerHTML=`<b>${$$('.g').reduce((n,x)=>n+Number(x.value),0)} puntos</b>`};$$('.g').forEach(x=>x.onchange=calc)}

async function renderStudy(){const cards=await NurseDB.all('flashcards'),cases=await NurseDB.all('cases');const review=cases.filter(c=>c.review?.trim());$('#app').innerHTML=`${section('Repasar hoy')}<div class="card hero"><h2>${cards.length?cards.length:'Empieza tu banco'} de flashcards</h2><p class="muted">Convierte dudas y aprendizajes del prácticum en repaso activo.</p><button class="btn secondary" id="newCard">Nueva flashcard</button></div>${section('Desde tus prácticas')}<div class="list">${review.length?review.slice(0,8).map(c=>`<div class="list-row"><div class="grow"><strong>${esc(c.diagnosis)}</strong><span class="small muted">${esc(c.review)}</span></div></div>`).join(''):'<div class="empty">Marca “qué quiero revisar” al registrar casos y aparecerá aquí.</div>'}</div>${section('Banco de tarjetas')}<div class="list" id="cardList"></div>`;$('#cardList').innerHTML=cards.length?cards.map(c=>`<button class="list-row" data-card="${c.id}"><div class="grow" style="text-align:left"><strong>${esc(c.q)}</strong><span class="small muted">Toca para ver respuesta</span></div></button>`).join(''):'<div class="empty">Aún no tienes tarjetas.</div>';$('#newCard').onclick=openNewCard;$$('[data-card]').forEach(b=>b.onclick=async()=>{const c=await NurseDB.get('flashcards',b.dataset.card);modal(`<div class="modal-head"><h2>Flashcard</h2><button class="icon-btn" onclick="closeModal()">×</button></div><div class="card"><strong>${esc(c.q)}</strong></div><div class="card"><p>${esc(c.a)}</p></div><button class="btn danger" id="delCard">Eliminar</button>`);$('#delCard').onclick=async()=>{await NurseDB.remove('flashcards',c.id);closeModal();render()}})}
function openNewCard(){modal(`<div class="modal-head"><h2>Nueva flashcard</h2><button class="icon-btn" onclick="closeModal()">×</button></div><form id="cardForm"><label>Pregunta</label><textarea class="field" name="q" required></textarea><label>Respuesta</label><textarea class="field" name="a" required></textarea><div class="modal-actions"><button class="btn primary">Guardar</button></div></form>`);$('#cardForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);await NurseDB.put('flashcards',{id:id(),q:f.get('q'),a:f.get('a'),createdAt:new Date().toISOString()});closeModal();render();toast('Tarjeta creada')}}

async function openTasks(){const tasks=await NurseDB.all('tasks');modal(`<div class="modal-head"><h2>Pendientes</h2><button class="icon-btn" onclick="closeModal()">×</button></div><form id="taskForm" style="display:flex;gap:8px"><input class="field" name="title" placeholder="Nueva tarea" required><button class="btn primary">+</button></form><div id="taskList" class="list" style="margin-top:12px"></div>`);const paint=async()=>{const t=await NurseDB.all('tasks');$('#taskList').innerHTML=t.map(x=>`<label class="list-row"><input type="checkbox" data-task="${x.id}" ${x.done?'checked':''}><span class="grow">${esc(x.title)}</span><button type="button" class="icon-btn" data-task-del="${x.id}">×</button></label>`).join('')||'<div class="empty">Sin pendientes.</div>';$$('[data-task]').forEach(c=>c.onchange=async()=>{const x=await NurseDB.get('tasks',c.dataset.task);x.done=c.checked;await NurseDB.put('tasks',x)});$$('[data-task-del]').forEach(b=>b.onclick=async()=>{await NurseDB.remove('tasks',b.dataset.taskDel);paint()})};paint();$('#taskForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);await NurseDB.put('tasks',{id:id(),title:f.get('title'),done:false});e.target.reset();paint()}}

async function openICDSearch(initial=''){if(!state.settings.icdWorker){toast('Configura primero la URL del Worker CIE en Prácticum.');return;}modal(`<div class="modal-head"><h2>Buscar CIE-11</h2><button class="icon-btn" onclick="closeModal()">×</button></div><div style="display:flex;gap:8px"><input class="field" id="icdQ" value="${esc(initial)}"><button class="btn primary" id="icdGo">Buscar</button></div><div id="icdResults" style="margin-top:12px"></div>`);$('#icdGo').onclick=async()=>{const q=$('#icdQ').value.trim();if(q.length<2)return;$('#icdResults').innerHTML='<div class="empty">Buscando…</div>';try{const base=state.settings.icdWorker.replace(/\/$/,'');const r=await fetch(`${base}/icd/search?q=${encodeURIComponent(q)}`);const j=await r.json();const arr=j.destinationEntities||[];$('#icdResults').innerHTML=arr.slice(0,20).map((x,i)=>`<button class="list-row icd-pick" data-i="${i}"><div class="grow" style="text-align:left"><strong>${esc((x.title||'').replace(/<[^>]+>/g,''))}</strong><span class="small muted">${esc(x.theCode||x.code||'')}</span></div></button>`).join('')||'<div class="empty">Sin resultados.</div>';$$('.icd-pick').forEach(b=>b.onclick=()=>{const x=arr[Number(b.dataset.i)],title=(x.title||'').replace(/<[^>]+>/g,'');closeModal();$('#diagnosis').value=title||$('#diagnosis').value;$('#icdCode').value=x.theCode||x.code||'';$('#icdChosen').textContent=`CIE-11: ${x.theCode||x.code||''} · ${title}`;});}catch(e){$('#icdResults').innerHTML=`<div class="notice">${esc(e.message)}</div>`}}}

async function openGlobalSearch(){const [cases,procs,meds,cards]=await Promise.all(['cases','procedures','meds','flashcards'].map(NurseDB.all));modal(`<div class="modal-head"><h2>Buscar</h2><button class="icon-btn" onclick="closeModal()">×</button></div><input class="field" id="globalQ" autofocus placeholder="Patología, técnica, medicamento, tarjeta…"><div id="globalResults"></div>`);$('#globalQ').oninput=e=>{const q=e.target.value.toLowerCase().trim();if(q.length<2){$('#globalResults').innerHTML='';return;}const rows=[];cases.filter(x=>(x.diagnosis+x.context).toLowerCase().includes(q)).slice(0,5).forEach(x=>rows.push(`<button class="list-row" onclick="closeModal();openCase('${x.id}')"><span class="pill">Caso</span><div class="grow" style="text-align:left"><strong>${esc(x.diagnosis)}</strong></div></button>`));procs.filter(x=>x.name.toLowerCase().includes(q)).slice(0,5).forEach(x=>rows.push(`<button class="list-row" onclick="closeModal();openProcedure('${x.id}')"><span class="pill">Batea</span><div class="grow" style="text-align:left"><strong>${esc(x.name)}</strong></div></button>`));meds.filter(x=>x.name.toLowerCase().includes(q)).slice(0,5).forEach(x=>rows.push(`<div class="list-row"><span class="pill">Rx</span><div class="grow"><strong>${esc(x.name)}</strong></div></div>`));cards.filter(x=>(x.q+x.a).toLowerCase().includes(q)).slice(0,5).forEach(x=>rows.push(`<div class="list-row"><span class="pill">Estudio</span><div class="grow"><strong>${esc(x.q)}</strong></div></div>`));$('#globalResults').innerHTML=`<div class="list" style="margin-top:12px">${rows.join('')||'<div class="empty">Sin resultados locales.</div>'}</div>`}}

window.closeModal=closeModal; window.openCase=openCase; window.openProcedure=openProcedure;
boot();
